### ISSUE TITLE
events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by hoky5611** [SKT-ThingPlug/thingplug-starter-kit#26]
Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/root/thingplug-starter-kit/node_modules/mqtt/lib/client.js:735:9)
    at MqttClient._handlePacket (/root/thingplug-starter-kit/node_modules/mqtt/lib/client.js:296:12)
    at process (/root/thingplug-starter-kit/node_modules/mqtt/lib/client.js:238:12)
    at Writable.writable._write (/root/thingplug-starter-kit/node_modules/mqtt/lib/client.js:248:5)
    at doWrite (/root/thingplug-starter-kit/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/root/thingplug-starter-kit/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/root/thingplug-starter-kit/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

![1](https://cloud.githubusercontent.com/assets/21697810/21921036/871ffad0-d9a8-11e6-9108-d7c9ce1f8b47.jpg)
![2](https://cloud.githubusercontent.com/assets/21697810/21921040/8b0d5fd4-d9a8-11e6-9e17-7476b529dd24.jpg)

**Comment by brianjang** [comment]
please see the patch as below : (you can resolve this issue)
https://github.com/SKT-ThingPlug/thingplug-starter-kit/pull/27

**Comment by ThingPlug** [comment]
서버 인증 변경으로 인해 패치 진행되었습니다.
감사합니다.
